#!/usr/bin/bash

n=$(basename $0)
if [ "$n" == 'gatk' ]; then
  n=$1
  shift
fi
if [ -z "$n" ]; then
  echo "Usage: $0 <application> [<parameters>]"
else
  echo exec java `eval echo $GATK_JAVA_OPTS` -jar "${GATK_HOME}/GenomeAnalysisTK.jar" "$n" "$@"
fi
exit 1
